### ISSUE TITLE
chromium-no-sse2 removed from AUR

### ISSUE THREAD

**Issue by andreas--e** [graysky2/chromium-no-sse2-patch#1]
I wonder where it's gone to and who deleted it?

OK, v41 is current, but TBH I'd rather have a working Chromium on my Athlon XP machine than none at all. Plus, it's a kind of protest thing, denoting that I won't let myself being locked out by some greedy product managers that don't have anything in mind but force people to upgrade their hardware.
Linux *WAS* always designed to run on older/old hardware, and hence this philosophy should not be dropped because some bureaucrats say it should.

**Comment by graysky2** [comment]
I asked to have ti pulled from the AUR since I am unable to update it.

**Comment by andreas--e** [comment]
Thanks for the quick reply. So you did this yourself? This is sad to hear. Well, maybe I can at least get a 36.x or 37.x version to work with your patch. Although it will take me lots of time, I won't allow myself getting locked out that impudent way. Speaking of impudent: I've yet to see any more impudent behavior of developers as I did recently: https://code.google.com/p/chromium/issues/detail?id=348761 What do these folks think they are?? Call us "zero Linux users with non-SSE2 CPUs". Not only did this make me really angry, but also willing to put up a fight. :) Since I won't let myself be treated like this!!

**Comment by graysky2** [comment]
If you get this working with the v41 release, feel free to send a PR.
